In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt



In [2]:
class Layer(object):
    def __init__ (self, prevNodes, currNodes):
        #initialize the current layer with number of inputs incomming and expected output of the layers
        # Numer of input and output nodes
        self.prevNodes = prevNodes + 1    #Bias also counted as a neuron 
        self.currNodes = currNodes
        result_array = np.full(currNodes, 0)
		# Random initilization of Matrix of weights init + bias weight
        self.weights = np.round(np.random.rand(self.prevNodes, self.currNodes) - 0.5, 2)

    def activation_stack(self,activation_stack):
        # defines the stack for identifing which activation func is applied on which neuron respectively 
        self.activation = activation_stack

    def activationFunc(self,input):
        
        opertaion = [
           1 / (1 + np.exp(-x)),
            np.maximum(0, x),
            np.tanh(x)
            ]
        
        for x in range(len(input)):
            input[x] = opertaion[self.activation[x]](input[x])
        return input
   
    def fwd(self, input): #foward pass
        # Add the bias value to the input
        self.input = np.concatenate((input, [[1]]), axis=1)
        # Sum the inputs and normalize for each output; dot product of pervious inputs and outputs
        sum = np.dot(self.input, self.weights)
        self.output = activationFunc(sum)
        print (self.output)
        return self.output
    

In [1]:
class NeuralNetwork(object):

	def __init__ (self, features, hiddenNeurons, classes, hiddenLayers = 1):

		# Create the first layer(DEFAULT)
		self.layerStack = np.array([Layer(features, hiddenNeurons)])

		# Create the hidden layers, WILL CREATE MULTIPLE HIDDEN LAYER DEPENDING UPON THE INPUT PARAM
		for x in range(hiddenLayers - 1):
			self.layerStack = np.append(self.layerStack, [Layer(hiddenNeurons, hiddenNeurons)])

		# Create the output layer(DEFAULT)
		self.layerStack = np.append(self.layerStack, [Layer(hiddenNeurons, classes)])

	def def_weight(self,matrix,hiddenlayer=1):
		self.layerStack[hiddenlayer].weights = matrix

	def def_activation(self,hiddenlayer):
		
		
	def eval(self, input):
        # Forward the signal through the layers
		lastInput = input
		for l in self.layerStack:
			lastInput = l.fwd(lastInput)

		return lastInput
	
	def train(self, input, target, iterations = 10000):
		for j in range(input.shape[0]):
				 # For each input vector in the data get the output
				inputVector = input[j]
				out = self.eval(inputVector)
				print(f"output for input vector {j}: {out} ")

	

IndentationError: expected an indented block after function definition on line 18 (2427288642.py, line 21)

In [11]:
input = np.matrix([[0, 0],
               [1, 0],
               [0, 1],
               [1, 1]])
weight =  np.matrix([[0, 0],
               [1, 0],
               [0, 1],
               [1, 1]])

In [12]:

network = NeuralNetwork(2, 3, 2)
network.train(input,1)  

[[0.4875026  0.42311474 0.4875026 ]]
[[0.41276484 0.35848372]]
output for input vector 0: [[0.41276484 0.35848372]] 
[[0.41095957 0.47751518 0.4329071 ]]
[[0.40716987 0.35255036]]
output for input vector 1: [[0.40716987 0.35255036]] 
[[0.60587367 0.32739298 0.42555748]]
[[0.42857989 0.37145576]]
output for input vector 2: [[0.42857989 0.37145576]] 
[[0.52996405 0.37754067 0.37285223]]
[[0.42313121 0.36588853]]
output for input vector 3: [[0.42313121 0.36588853]] 
