In [7]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [8]:
class Layer(object):
    def __init__ (self, inNodes, outNodes):
        #initialize the current layer with number of inputs incomming and expected output of the layers
        # Numer of input and output nodes

        self.inNodes = inNodes + 1    #Bias also counted as a neuron 
        self.outNodes = outNodes
        self.activation = np.full(outNodes, 0)
        
		# Random initilization of Matrix of weights init + bias weight
        self.weights = np.round(np.random.rand(self.inNodes, self.outNodes) - 0.5, 2)

    def desc_layer(self):
        print("--------------------------------------------------")
        print(f"IN NODE + bias: {self.inNodes-1}+1\nOUT NODES: {self.outNodes}")
        print(f"weight: {self.weights}")
        print(f"[0]-sigmoid\n[1]-realu\n[3]-tanh\nActivation_stack_neuron: {self.activation}")
        print("--------------------------------------------------\n")
    
    
    def activation_stack(self,activation_stack):
        # defines the stack for identifing which activation func is applied on which neuron respectively 
        self.activation = activation_stack

    def activationFunc(self,output):
        # un-optimized yet, need to be improved 
        # problems with np.matrix leading to typecasting with np.array for element itterations 
        
        output = np.array(output)
        opertaion = [
          lambda x: 1 / (1 + np.exp(-x)),
            lambda x: np.maximum(0, x),
            lambda x: np.tanh(x)
            ] 
        for index in range(len(output[0])):
            output[0][index] = opertaion[self.activation[index]](output[0][index])  
        return np.matrix(output) 
   
    def fwd(self, input): #foward pass
        # Add the bias value to the input
        self.input = np.concatenate((input, [[1]]), axis=1)
        # Sum the inputs and normalize for each output; dot product of pervious inputs and outputs
        sum = np.dot(self.input, self.weights)
        self.output = self.activationFunc(sum)
        print (self.output)
        return self.output
    

In [9]:
class NeuralNetwork(object):

	def __init__ (self, features, hiddenNeurons, classes, hiddenLayers = 1):

		# Create the first layer(DEFAULT)
		self.layerStack = np.array([Layer(features, hiddenNeurons)])

		# Create the hidden layers, WILL CREATE MULTIPLE HIDDEN LAYER DEPENDING UPON THE INPUT PARAM
		for x in range(hiddenLayers - 1):
			self.layerStack = np.append(self.layerStack, [Layer(hiddenNeurons, hiddenNeurons)])

		# Create the output layer(DEFAULT)
		self.layerStack = np.append(self.layerStack, [Layer(hiddenNeurons, classes)])

	def def_weight(self,matrix,hiddenlayer=1):
		self.layerStack[hiddenlayer].weights = matrix

	def desc_network(self):
		for x in self.layerStack:
			x.desc_layer()

	def def_layer_activation(self,stack,layer):
		self.layerStack[layer].activation_stack(stack)
		
		
	def eval(self, input):
        # Forward the signal through the layers
		lastInput = input
		for l in self.layerStack:
			lastInput = l.fwd(lastInput)
		return lastInput
	
	def train(self, input, target, iterations = 10000):
		for j in range(input.shape[0]):
				 # For each input vector in the data get the output
				inputVector = input[j]
				out = self.eval(inputVector)
				print(f"output for input vector {j}: {out}\n\n")

	

In [10]:
input = np.matrix([[0, 0],
               [1, 0],
               [0, 1],
               [1, 1]])

In [11]:
network = NeuralNetwork(2, 3, 2)
network.def_layer_activation([0,0,1],0)
network.desc_network()

--------------------------------------------------
IN NODE + bias: 2+1
OUT NODES: 3
weight: [[-0.39 -0.42 -0.08]
 [-0.18  0.41  0.06]
 [-0.12  0.26 -0.03]]
[0]-sigmoid
[1]-realu
[3]-tanh
Activation_stack_neuron: [0, 0, 1]
--------------------------------------------------

--------------------------------------------------
IN NODE + bias: 3+1
OUT NODES: 2
weight: [[ 0.07 -0.02]
 [ 0.09 -0.01]
 [ 0.43 -0.23]
 [ 0.24  0.05]]
[0]-sigmoid
[1]-realu
[3]-tanh
Activation_stack_neuron: [0 0]
--------------------------------------------------



In [12]:
network.train(input,1)  

[[0.47003595 0.56463629 0.        ]]
[[0.58023052 0.50873734]]
output for input vector 0: [[0.58023052 0.50873734]]


[[0.37519353 0.46008512 0.        ]]
[[0.57631673 0.50947269]]
output for input vector 1: [[0.57631673 0.50947269]]


[[0.42555748 0.66150316 0.03      ]]
[[0.58473073 0.506993  ]]
output for input vector 2: [[0.58473073 0.506993  ]]


[[0.33403307 0.5621765  0.        ]]
[[0.577856   0.50942328]]
output for input vector 3: [[0.577856   0.50942328]]


